version: "3.9"

services:
  api:
    build: ./whisky_api
    container_name: whisky_api
    volumes:
      - ./database:/database
    environment:
      - DATABASE_URL=sqlite:////database/whisky.db
    depends_on:
      - db
    ports:
      - "7899:7899"

  webapp:
    build: ./whisky_webapp 
    container_name: whisky_webapp
    volumes:
      - /exports/nas/wilbrink.a/whisky_project/whisky_data:/exports/nas/wilbrink.a/whisky_project/whisky_data
    environment:
      - DATABASE_URL=http://api:7899
    depends_on:
      - api
    ports:
      - "8000:8000"
    command:
      - /bin/sh
      - -c 
      - |
        python website/manage.py migrate
        python website/manage.py runserver 0:8000
 

